### ISSUE TITLE
git-crypt no gpg secret key available to unlock this repository

### ISSUE THREAD

**Issue by uioporqwerty** [AGWA/git-crypt#143]
I'm trying to unlock a repository on another computer. From PC A I exported the private key as `private.asc` and then I import it on PC B using `gpg --import private.asc`. However when I run `git-crypt unlock` I get the following error:

```
$ git-crypt unlock
Error: no GPG secret key available to unlock this repository.
To unlock with a shared symmetric key instead, specify the path to the symmetric key as an argument to 'git-crypt unlock'.
```

Why does this happen? I'm using Windows 7 and MSYS2 64 bit terminal.

**Comment by arrfab** [comment]
Well, I do't know how you have extracted the private key, but at least that's not the correct way to import it back in secring : --import would only import a public key, if you want to import the private key part, you need : 
gpg --allow-secret-key-import --import private.key

**Comment by uioporqwerty** [comment]
So on PC A I ran the following commands to export the public and secret keys.

```
gpg --export -a 40CD5608 > public.asc
gpg --export-secret-keys -a 40CD5608 > secret.asc
```

which I then transfer both files to PC B and then run the command previously to import the private key `gpg --import private.asc`.

I deleted the keys with `gpg --delete-secret-key 40CD5608` and `gpg --delete-key 40CD5608` which cleared out my keyring. But after running `gpg --allow-secret-key-import --import secret.asc` the git-crypt command still returns the error above.

**Comment by uioporqwerty** [comment]
Nevermind, guess it is resolved now.

**Comment by Jomik** [comment]
@uioporqwerty Should probably close this if it is resolved :+1:

**Comment by wfxr** [comment]
Oh I find what's wrong.
I use ssh over pip to import key as this:
```
gpg --export-secret-keys wenxuangm@gmail.com | ssh <remote> gpg --allow-secret-key-import --import
```
There is no error message. But actually `--allow-secret-key-import` option does not take effect.
When I copy the key and run `gpg --allow-secret-key-import --import secret.asc` on the new machine, the secret key was successfully imported. And `git-crypt unlock` does not complain anymore.

**Comment by medved-s** [comment]
I have the same issue now ("Error: no GPG secret key available to unlock this repository."). 
`gpg --list-keys`
returns the keys. Who can help me? @uioporqwerty ?
