### ISSUE TITLE
Git-crypt workflow - deployment to multiple servers or circleci/travisci

### ISSUE THREAD

**Issue by AvnerCohen** [AGWA/git-crypt#153]
Trying to understanding the full workflow of a git-crypt based secret keeping solution.

The tool itself works pretty nicely when on a dev machine, even scaling to multiple developers seems to work fine.

However, it is not clear to me how will this work when deployed to a multiple servers on a cloud, some are created on-demand:

1. Challenge of unattended creation of GPG key on the new server (someone needs to create the passphrase, or is it in a source control, and than, what is all this even worth?)

2. Once a GPG is created, how is it being added to the ring?

Say we decide to skip (1) and just share a key across servers, how is the passphrase being supplied as part of the "git-crypt unlock" process when a new server is created?

(
Tried a stack-overflow first:
https://stackoverflow.com/questions/51168048/git-crypt-workflow-deployment-to-multiple-servers-or-circleci-travisci

Will try here as well.
)

**Comment by alerque** [comment]
As I commented on SO, I'm nut sure why this question is directed at `git-crypt`, shouldn't adding a key to a GPG ring or injecting some other passphrase variable be part of your system setup and deployment? What `git-crypt` handles is farther down the pipeline than where than sort of system prep should happen. What platform are you using?

**Comment by alerque** [comment]
I've taken a stab at answering this on SO. Perhaps if that doesn't answer it for you you could edit your question there to clarify or ask something specific about AWS CloudFormation. I know there is  an EC2 API for injecting secrets including key files into an API that can be read from inside the machines, but that is somewhat out of scope for this Github issue. I suggest this issue can probably be closed as `git-crypt` has relatively little role to play in this equation.

**Comment by AvnerCohen** [comment]
@alerque thank you very much for taking the time to review this. Hopefully others will benefit from this as well. If anything more is needed, will continue that on SO.
