### ISSUE TITLE
Couldnt decode my files. Keys directory is empty? What to do now?

### ISSUE THREAD

**Issue by asantoso** [AGWA/git-crypt#171]
Committed some files. Pushed to repo checked that it works. Tried to unlock those files back but failed.
Noticed that the .git/git-crypt/keys directory is empty. 
What to do now? 
Other strange thing is that git-crypt starts giving errors on directory outside of the repo it was initialized in.

**Comment by asantoso** [comment]
Thankfully I only tested on small number of unimportant files, otherwise I would be pulling hairs out.
Bad terrifying experience I am now switching to other tools

**Comment by alerque** [comment]
This sounds very much like you have nested git repositories and got linked up on the wrong one. You say you "checked that it works", but what exactly did you check? Are you using  a symmetric key or GPG?
