### ISSUE TITLE
GitKraken integration

### ISSUE THREAD

**Issue by cwolcott** [AGWA/git-crypt#176]
I have git-crypt working just fine with a test repository using git command line, but am having issues using GitKraken. Has anyone used GitKraken and git-encrypt?

My issue in GitKraken is when I choose an edited file and select "Stage File" it does not get encrypted like it does when I use the command line "git add .".  Any thoughts?

**Comment by natanverdes** [comment]
It happens to me too, I don't know if it happens to any git GUI or because of GitKraken. With merge and checkout happens too.

**Comment by alerque** [comment]
Does GitKraken respect _anything_ from `.gitattributes`? I suspect this might be a problem with their use of git plumbing rather than a `git-crypt` issue at all. Can we confirm that it respects anything in there such as smudge/clean filters at all?

**Comment by cwolcott** [comment]
Found a similar discussion on [reddit](https://www.reddit.com/r/git/comments/admsh1/gitkraken_not_using_gitattributes_filters/)

**Comment by robsman** [comment]
With SmartGit, it works just fine, but GitKraken does not encrypt upon staging.

**Comment by Achoobert** [comment]
👋 I would like this feature in GitKracken

**Comment by AGWA** [comment]
This is not a git-crypt issue.
