### ISSUE TITLE
Error: The filename or extension is too long.

### ISSUE THREAD

**Issue by theoryshaw** [AGWA/git-crypt#186]
I get this error when unlocking on windows...
https://gist.github.com/theoryshaw/e8672a09fbaa20ba52a8bedaf95b3a96

These were my settings before running the command..

- Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
  - Set LongPathsEnabled
    - Value data: 1
- `git config --system core.longpaths true`

This is the repo, if curious: https://github.com/OpeningDesign/CTR

**Comment by AGWA** [comment]
Most likely related to #150

**Comment by theoryshaw** [comment]
Thanks. As i'm reading that, there's no fix at the moment?

**Comment by AGWA** [comment]
Applying the patch should fix the problem, at a performance cost which might be significant on Windows.

**Comment by AGWA** [comment]
I'm assuming this has been fixed by #150 but feel free to re-open if not.

**Comment by theoryshaw** [comment]
Not sure. Am waiting for a someone to create a windows executable to test.
