### ISSUE TITLE
A read-only GitHub user cannot disable encryption 

### ISSUE THREAD

**Issue by nodesocket** [AGWA/git-crypt#198]
If a GitHub user only has read permissions `.i.e. deploy key` they cannot disable git-crypt on a repo right? I want to use [multiple keys](https://github.com/AGWA/git-crypt/blob/master/doc/multiple_keys.md) to limit access depending on the user.

For example:

```
git clone git@github.com:FooInc/AcmeProject.git
cd AcmeProject
git-crypt unlock  # decrypts only a select number of encrypted files based on their gpg user
rm -f .gitattributes
git add .
git commit -am "removed .gitattributes"
```

They don't have access to all decrypted files now do they?

**Comment by AGWA** [comment]
I don't know what "deploy key" means, but if a user can only read - not write - the repository, they can't mess with .gitattributes to disable encryption.
