### ISSUE TITLE
Question about committed keys to .git-crypt

### ISSUE THREAD

**Issue by spamwax** [AGWA/git-crypt#203]
Regarding using
`git-crypt add-gpg-user KEYID`
in order to add a user/key the REAME says that

> Note: git-crypt add-gpg-user will add and commit a GPG-encrypted key file in the .git-crypt directory of the root of your repository

I'd like to know if this is the private key that's been committed or the public key, and if it is the public key why it's been encrypted/protected?

**Comment by Vad1mo** [comment]
the symetric key is encrypted with the pub key of the user with the ID, so that only the user that has the private key can encrypt the file.
