### ISSUE TITLE
openssl/opensslconf.h: No such file or directory

### ISSUE THREAD

**Issue by FilipLaurentiu** [AGWA/git-crypt#206]
> filip@filip-pc:~/Desktop/git-crypt$ make
> g++ -Wall -pedantic -Wno-long-long -O2 -std=c++11   -c -o git-crypt.o git-crypt.cpp
> g++ -Wall -pedantic -Wno-long-long -O2 -std=c++11   -c -o commands.o commands.cpp
> g++ -Wall -pedantic -Wno-long-long -O2 -std=c++11   -c -o crypto.o crypto.cpp
> g++ -Wall -pedantic -Wno-long-long -O2 -std=c++11   -c -o gpg.o gpg.cpp
> g++ -Wall -pedantic -Wno-long-long -O2 -std=c++11   -c -o key.o key.cpp
> g++ -Wall -pedantic -Wno-long-long -O2 -std=c++11   -c -o util.o util.cpp
> g++ -Wall -pedantic -Wno-long-long -O2 -std=c++11   -c -o parse_options.o parse_options.cpp
> g++ -Wall -pedantic -Wno-long-long -O2 -std=c++11   -c -o coprocess.o coprocess.cpp
> g++ -Wall -pedantic -Wno-long-long -O2 -std=c++11   -c -o fhstream.o fhstream.cpp
> g++ -Wall -pedantic -Wno-long-long -O2 -std=c++11   -c -o crypto-openssl-10.o crypto-openssl-10.cpp
> crypto-openssl-10.cpp:31:10: fatal error: openssl/opensslconf.h: No such file or directory
>    31 | #include <openssl/opensslconf.h>
>       |          ^~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make: *** [<builtin>: crypto-openssl-10.o] Error 1
> 
> 

I have openssl install
> filip@filip-pc:~/Desktop/git-crypt$ openssl version
> OpenSSL 1.1.1f  31 Mar 2020

I encounter a error when I try to install git-crypt on ubuntu 20. 
Any idea?

**Comment by FilipLaurentiu** [comment]
> sudo apt install libssl-dev

**Comment by AbdullahKady** [comment]
> I found the fix for this:
> 
> > sudo apt install libssl-dev

Thank you, that was fast enough :)
Welcome to focal fossa :partying_face:

**Comment by samjewell** [comment]
On macOS (Apple M1 chip, Arm64 arch, for me) I did the following:

- Install `openssl` through Homebrew
- Export the environment variables PATH, LDFLAGS and CPPFLAGS in my bash session as recommended in the post install message for `brew install openssl`

Then `make` worked fine for me 🎉

**Comment by aleks-mariusz** [comment]
@fabszabo did you also do the following?

> * Export the environment variables PATH, LDFLAGS and CPPFLAGS in my bash session as recommended in the post install message for `brew install openssl`
