### ISSUE TITLE
Clarify documentation

### ISSUE THREAD

**Issue by dbinfl** [AGWA/git-crypt#208]
Hello,
We have just set a secure repo using git-crypt and have enabled it in Azure Devops release pipelines. We are happy with the results. However, getting that sorted out revealed some apparent shortcomings in the documentation, which states "That's all you need to do - after git-crypt is set up (either with git-crypt init or git-crypt unlock), you can use git normally - encryption and decryption happen transparently."
In our experience it was not "transparent", Having to lock the repo again is not mentioned. And particularly with how it relates to pushing changes back to git, order of operation is important. We found this these steps to be necessary:
		cd <repo>
		git status
		git pull (if needed)
		git-crypt unlock <path to key>
		make changes as needed
		git add *
		git commit -a
		git-crypt lock
		git push

Some clarity about this in the documentation would be helpful and appreciated.
Thanks,

**Comment by AGWA** [comment]
You do not need to lock before pushing.  If pushing without locking doesn't work, please open a new issue describing in detail what happened.
