### ISSUE TITLE
expand key ID references in commit messages

### ISSUE THREAD

**Issue by ktdreyer** [AGWA/git-crypt#253]
https://evil32.com/ explains why we should reduce the use of 32-bit key IDs.

git-crypt writes commit messages with short key IDs:

```c++
// given a key fingerprint, return the last 8 nibbles
std::string gpg_shorten_fingerprint (const std::string& fingerprint)
{
	return fingerprint.size() == 40 ? fingerprint.substr(32) : fingerprint;
}
```

Could we write the full fingerprints instead?

**Comment by AGWA** [comment]
Good idea.

To be clear, git-crypt already uses exclusively full fingerprints internally.  The commit message was the only place short IDs were being used.
