### ISSUE TITLE
build using MacPorts instructions

### ISSUE THREAD

**Issue by atmosx** [AGWA/git-crypt#257]
Unfortunately, there is no [MacPorts](https://www.macports.org/) support for `git-crypt` yet. To compile nuder MacPorts with OpenSSL support:

```
git clone https://github.com/AGWA/git-crypt.git
cd git-crypt
export CPPFLAGS="-I/opt/local/libexec/openssl11/include -I/opt/local/include"
make
make install PREFIX=$HOME/Programs
```

LibreSSL is another alternative, instructions are similar.

> **NOTE**: The path `$HOME/Programs` is a personal preference for software I install manually, make sure `$HOME/Programs/bin` is in your `$PATH`.

To find the specific OpenSSL path, in case you're not using openssl11 with Macports:

```
pkg-config openssl --libs
-L/opt/local/libexec/openssl11/lib -lssl -lcrypto
```

Cheers!

**Comment by quentinmit** [comment]
I'm not sure what you mean by "no MacPorts support for `git-crypt` yet".  It's already packaged and available in MacPorts: https://ports.macports.org/port/git-crypt/

**Comment by atmosx** [comment]
> I'm not sure what you mean by "no MacPorts support for `git-crypt` yet". It's already packaged and available in MacPorts: https://ports.macports.org/port/git-crypt/

That's correct, I missed it! When I installed `git-crypt` for the first time wasn't part of the ports tree. We can close this ticket then.
