### ISSUE TITLE
Rename key

### ISSUE THREAD

**Issue by KommuSoft** [AGWA/git-crypt#27]
How can one rename the key (that's easy) and then relink the `git-crypt` repository with the renamed key? Is a simple init sufficient, or does one has to `git clone` the repository again and relink it by `init` it?

**Comment by krish7919** [comment]
Sorry for commenting on this old issue but I tried this out just now.

This does not seem to work. As with everything else, there seems to be no documentation.

1. `git clone` and `git-crypt unlock -k old_key_file` works fine. Now I have a repo with decrypted files.
2. `git-crypt init -k new_key` and `git-crypt export-key -k new_key /tmp/new_key_file` works too.
3. But now the repo has no `diff`. How am I supposed to update the key? A `push -f` hasn't helped. Does this mean that I should have some work done and this change needs some modification of the encrypted files?
