### ISSUE TITLE
Git-crypt doesn't decrypt

### ISSUE THREAD

**Issue by Crims-on** [AGWA/git-crypt#282]
I tried cloning my github repo with a configuration to encrypt all files and when I check if the files are encrypted using `git-crypt status` it says that none of the files are encrypted even though they clearly are with a git-crypt signature in the file. `git-crypt unlock ../key` adds the key to the keys directory but doesn't decrypt any files and when running `git-crypt status` again it says the same thing. I get no errors or anything so I don't know what is wrong

This problem is occuring on windows with version 0.7.0 prebuilt

**Comment by alerque** [comment]
> with a configuration to encrypt all files

How exactly did you configure this? It sounds like you might have configured your repository to encrypt the `git-crypt` tracked files as well as your own, hence leaving nothing readable to `git-crypt unlock`. You need to only encrypt *your content files* in the repo, not wildcard the whole thing.
