### ISSUE TITLE
Add command to see encrypted files

### ISSUE THREAD

**Issue by armetiz** [AGWA/git-crypt#29]
Hi,
I'm new user of git-crypt, and I really appreciate the git integration that you've made.

Right now, when I `git add file.txt` I'm not sure this file is encrypted.
I miss a command like `git-crypt list-secured-files` that could display secured file.

What do you think about it ? Maybe you have an other solution ?

Regards,
Thomas.

**Comment by davidwhthomas** [comment]
Just noting, you can also specify a sub-directory to check, with thanks

e.g:

`git-crypt status dirname`
