### ISSUE TITLE
initial unlock not decrypting under Git 2.2.2 and higher

### ISSUE THREAD

**Issue by philpennock** [AGWA/git-crypt#32]
Context: we're using git-crypt in a team environment, with keys manually shared via PGP (predates the automatic PGP support in git-crypt), and things have been working well.

A colleague tried to unlock a fresh clone and did not end up with decrypted files.  I've tracked down resolution to `rm -rf areas-which-are-encrypted` followed by `git checkout areas-which-are-encrypted`.

This is with git 2.2.2 and git-crypt 0.4.1 on MacOSX.

It looks as though after an unlock, the initial pass to smudge the encrypted files is failing to do so; what I've seen so far, including reviewing recent git-crypt commits, leads me to suspect a regression in git rather than git-crypt, but I lack the knowledge of git internals and filters to debug this bad interaction sufficiently to file a report upstream, and figure you don't want your users filing error-filled interaction reports on the main lists and causing other git developers to hate on git-crypt, so am filing this report here with you, for further investigation and hopefully filing a more clue-filled report/patch with upstream git.

**Comment by AGWA** [comment]
Thanks for reporting this.  I've reproduced the problem under Git 2.2.2.  I will try bisecting Git to determine when this was introduced.

**Comment by AGWA** [comment]
This was introduced in git/git@c5326bd62b7e168ba1339dacb7ee812d0fe98c7c, which first appeared in Git 2.2.2.  As an optimization, Git now declines to check out a file if its mtime hasn't changed, even if the output of its smudge filter has changed.

I've just pushed d5670c95523ec3c6abb20e35bfceb635413dfb5e, which works around the issue by touching files' mtimes before checking them out.  I'll be releasing git-crypt 0.4.2 with this fix in the near future.

**Comment by philpennock** [comment]
Thank you -- very much appreciated. :)

**Comment by jonhadfield** [comment]
I had the same issue with OSX 10.2.2, Git 2.2.2 and an older version of git-crypt.
Now decrypting as expected after building from: https://github.com/AGWA/git-crypt/commit/5fd36a7ac50b5e9d483c9de9b38bbe98bd3f0c8b
Thanks.

**Comment by AGWA** [comment]
git-crypt 0.4.2, which contains this fix, has been released.  Thanks again, @philpennock, for reporting this!
