### ISSUE TITLE
Clarification on .gitattribute files.

### ISSUE THREAD

**Issue by skorokithakis** [AGWA/git-crypt#36]
I just tried the new git-crypt version, with asymmetric crypto, I ran `git-crypt init` on my new repo, and edited the `.git-crypt/.gitattributes` file to add the specs I wanted. However, I can't get git-crypt to actually encrypt the files. Am I supposed to move the `.gitattributes` file to the root dir of the repo?

```
21:24:40 $ cat .gitattributes 
*.secret filter=git-crypt diff=git-crypt
*.key filter=git-crypt diff=git-crypt
group_vars/*.yml filter=git-crypt diff=git-crypt
secret_keys.py filter=git-crypt diff=git-crypt

* !filter !diff
```

**Comment by AGWA** [comment]
You should leave the `.git-crypt/.gitattributes` file as-is, and create your own `.gitattributes` in the root of the repo to specify the files you want to encrypt.  (You can also put it in a sub-directory, if that's where the files you want to encrypt are.)

I can see how the `.git-crypt/.gitattributes` file created by git-crypt could be confusing - I'll have git-crypt add a comment to that file saying not to edit it.

**Comment by skorokithakis** [comment]
Oh, oops, thank you for that. Can you add something to the documentation? I was supremely confused by this new development.

**Comment by AGWA** [comment]
I'm going to leave the documentation as-is to keep it concise.  Instead, I've just changed git-crypt to add the following comment to `.git-crypt/.gitattributes`:

```
# Do not edit this file. To specify the files to encrypt, create your own
# .gitattributes file in the directory where your files are.
```

**Comment by skorokithakis** [comment]
Works for me, thanks!

**Comment by AGWA** [comment]
You posted the following to an unrelated ticket (#34):

> The above .gitattributes file still won't work for me. I did git-crypt init, git-crypt add-gpg-user 77ABF777 and committed, and cloning gives me a file called secret.key in plaintext. Is there some step I'm missing?

At what point was `secret.key` staged and committed to the repository?  git-crypt can't retroactively encrypt files, so you have to make sure not to add any sensitive files until *after* you've set up your `.gitattributes` file.

Also, what does the output of `git-crypt status secret.key` say?

**Comment by skorokithakis** [comment]
I'm just committing it now (after setting everything up). Status says:

```
 encrypted: deployment/roles/nginx/files/certs/secret.key *** WARNING: staged/committed version is NOT ENCRYPTED! ***
```

**Comment by AGWA** [comment]
Is it possible it was staged (i.e. with `git add`) before `.gitattributes` was in place?  If you're sure it wasn't, it sounds like Git isn't applying the filters properly - are you working exclusively from the command line, or is there a GUI in the mix?

To fix this, you can run  `git status --fix`, which will re-stage secret.key in encrypted form, after which you can commit it.  But after you do this, double-check `git log secret.key`- if it was ever committed unencrypted, you'll need to redact those commits.

**Comment by skorokithakis** [comment]
It was, indeed, staged before .gitattributes was in place, so I removed it and did it again. I don't want to commit plaintext files (hopefully `git reset --soft` doesn't send the undone commits to the server). I tried the `--fix` suggestion, but got:

```
Error: deployment/roles/nginx/files/certs/secret.key: still unencrypted even after staging
```

Could this be a GPG error?

**Comment by AGWA** [comment]
> still unencrypted even after staging

That means Git isn't applying the filters.  What version of Git are you using?  What's the output of `git config --get filter.git-crypt.clean`?

**Comment by skorokithakis** [comment]
I'm using git 1.9.1, but the problem is what your `git config` command shows: git doesn't know anything about the filters! I have no idea why... Should I maybe not have checked in the `.git-crypt/` dir? The docs were unclear about that.

**Comment by AGWA** [comment]
`git-crypt init` should have set up the filters.  I can't imagine what could have gone wrong.  Does your `.git/config` file show anything related to git-crypt at all?

git-crypt would have committed the `.git-crypt` directory itself so doing so yourself would have been at worst redundant.

**Comment by skorokithakis** [comment]
Huh, no, the filters aren't in `.git/config`. That's odd, I didn't touch them, and re-running the same commands in a different directory adds the filters just fine. `git-crypt init` isn't idempotent, sadly, so I will need to copy them over from that file. Is that safe?

**Comment by AGWA** [comment]
Yes, copying the lines over is safe.

**Comment by skorokithakis** [comment]
Okay, this is very odd. I re-ran `git-crypt init` and it worked, and the files are now encrypted. I have no idea what happened. Maybe I somehow reverted its initial commit and forgot about it? At any rate, thank you for your help, and keep up the good work, I love `git-crypt`.
