### ISSUE TITLE
Only encrypt specific words / lines in a file

### ISSUE THREAD

**Issue by dlo** [AGWA/git-crypt#4]
It might be nice to only encrypt the parts of the file that contain sensitive information, as opposed to the entire file.

**Comment by dsernst** [comment]
Could you use environment variables instead? Or your language's `import`, `require`, `include` etc?

**Comment by AGWA** [comment]
Hey, sorry for the extremely late reply to this issue.  I think this would add too much complexity to git-crypt for not enough gain, and there are much more pressing things to work on in git-crypt.  Using an inclusion mechanism like @dsernst suggested seems like the way to go, though if you have a use case in mind that couldn't be solved this way, I'd be interested in hearing it.

**Comment by dlo** [comment]
Hey @AGWA, no worries. There are lots of configuration files which can't execute or interpret code, so environment variables / dynamic code execution doesn't help much with that.

**Comment by AGWA** [comment]
@dlo But is there a downside to just encrypting the entire config file in those cases?

**Comment by dlo** [comment]
The downside is that diffs are pretty useless when the whole file is encrypted.

**Comment by AGWA** [comment]
git-crypt installs a diff driver, so (assuming you know the secret key) you can actually get useful diffs of the plaintext.

**Comment by dlo** [comment]
Locally, sure, but I was thinking more of the use case of sharing something like my dotfiles on GitHub.

**Comment by AGWA** [comment]
Ah, I see.  Indeed, there is a tradeoff - if you encrypt the whole file, you can no longer share the non-secret parts.

**Comment by anlutro** [comment]
Is this still considered out of scope? My usecase is using this for some configuration files which don't support any type of includes or conf.d behaviour. I'd like to be able to show the configuration to others on github, but there are passwords in the file.

Maybe this could be achieved by having some sort of pattern denoting encrypted parts of a file - `[[ENC[[encrypted-data-here]]ENC]]` or whatever, and then just search for occurances of that pattern and decrypt them. I guess the main challenge is, how do you keep track of where encryption starts/stops in the *decrypted* file/state.

**Comment by Cinderhaze** [comment]
Not specific to this project, but a tool used by puppet is https://github.com/voxpupuli/hiera-eyaml and https://github.com/sihil/hiera-eyaml-gpg.  It has an interesting ‘eyaml edit’ capability, but it always leaves parts of a file encrypted.  

It has a notation similar to what you mentioned, but only works on yaml files

**Comment by alerque** [comment]
@anlutro You don't have to be using a config file format that has an include behavior to implement the pattern. Just make the config file part of your build routine. Move the config to a source location and use a macro processor to combine it with the encrypted bits from another file to generate the "live" file in the format needed for consumption. The `m4` macro processor is a good standby for things like this, or any static templating language will work too.

**Comment by anlutro** [comment]
That's an option, but I like being able to edit my configuration files directly without having to run a build script to pre-process them.
