### ISSUE TITLE
Windows: git unlock using migrated key hangs

### ISSUE THREAD

**Issue by vorou** [AGWA/git-crypt#54]
I'm using the binary you provided [here](https://github.com/AGWA/git-crypt/pull/13#issuecomment-97869741).

I had a repo with git-crypt initialized already. `git-crypt unlock key` suggested me to migrate the key, which I did w/ `git-crypt migrate-key`. `git-crypt unlock new-key` hangs silently. I'd waited for about 3 minutes before shutting it down.

The output in Process Monitor looks like git-crypt is stuck in loop, polling some system folders which I don't think it supposed to be polling. I could email you the full log, if it helps.

**Comment by vorou** [comment]
To work around it I've tried to just init the repo w/ the new git-crypt after I cloned and decrypted it using the old git-crypt. It says `Error: this repository has already been initialized with git-crypt.`. Any way I can un-init the repo?

**Comment by AGWA** [comment]
You can un-init by running `git-crypt lock`.

I hope to investigate the hang soon, but haven't had time yet.

**Comment by AGWA** [comment]
I wasn't able to reproduce the hang.  Could you email the full log to me at andrew@agwa.name?  Hopefully it will help.  Also, a few questions:

1. How many files are in this repository?
2. What version of Git and of Windows are you running?
3. In what sort of environment are you running git/git-crypt?  (e.g. MinGW, cygwin)

**Comment by AGWA** [comment]
I'm almost 100% positive that this wasn't an indefinite hang, but rather `git-crypt unlock` being excruciatingly slow because of a workaround I recently deployed for Git 2.2.2.  Currently, `unlock` spawns a separate `git check-attr` process for every single file in the repository.  This is bad enough on Unix, and is probably terrible on Windows, which has much slower process creation than Unix.  I'm working on a solution and initial tests show a nearly 100x speedup on Unix.

**Comment by AGWA** [comment]
@vorou Could you try the following .exe to see if it fixes your program?

https://www.cloudmutt.com/s/git-crypt-4acb420/git-crypt.exe

**Comment by AGWA** [comment]
I haven't heard back, but I'm pretty sure this is fixed, and the fix is rolled into the recently-released 0.5.0.  You can reopen the bug if this isn't the case.

**Comment by kotlinski** [comment]
Can you put the git-crypt in a new release, so it would be easier to find?

**Comment by fancy967** [comment]
I do agree to include a windows binary in every new release later
