### ISSUE TITLE
.git-crypt/.gitattributes file should set binary status

### ISSUE THREAD

**Issue by dupuy** [AGWA/git-crypt#55]
Of course when I try to reproduce this, it isn't possible, but in two repositories I have used with git-crypt, when I use `git show` to display one of the commits created automatically by the `git-crypt add-gpg-user ...` command, it show garbage text diffs for the `.gpg` file associated with that user.  These are binary files, but as they are fairly short, there is a chance that they might contain enough plausible characters for Git to think they are some kind of 8-bit accented text.

This is a minor niggle (at least until somebody gets *extremely* unlucky on a Windows system and Git thinks a file is CRLF text and converts that to LF) but if the add-gpg-user command could make the content of the `.git-crypt/.gitattributes` file mark all GPG files within that directory as binary, it would eliminate even the remote possibility of this minor confusion.

FWIW, here is a transcript of the problem (and my local fix) in my repository; if you need to look at it in detail, I could push to a BitBucket private repo and share that with you.

```
$ git diff .git-crypt/.gitattributes
$ git show 2c331f3
commit 2c331f3c78259d557362e4585acff7260d8ed142
Author: Alexander Dupuy <alex.dupuy@mac.com>
Date:   Tue May 12 14:08:38 2015 +0200

    Add 1 git-crypt collaborator

    New collaborators:

        82A69645 Alexander Dupuy <alex@dupuy.us>

diff --git a/.git-crypt/keys/default/0/083382BAC0059BE3D6544C8B0DCF16F482A69645.
new file mode 100644
index 0000000..9d98379
--- /dev/null
+++ b/.git-crypt/keys/default/0/083382BAC0059BE3D6544C8B0DCF16F482A69645.gpg
@@ -0,0 +1,4 @@
+<85>^B^L^C<BB><EF><B5>^<85>_<9E>q^A^O<FE>-<8A>}^Rb<97>KHLOb<C0>^Z<E0>u<C1><97>T
+<8D><81><BC><CB>W'UF<8A>Y_<BB><A5>!^X<CC><EC>an<B0>T<D6><EA>^Y<F8>B<F5>`A<8D>@
+<BA>D<BE>ۤ<D7>X<D6>ȵ|o<C1>^N}<A8>}}yH<CF>︇>^MN_X<D1>=Q4<97><CC>dʱ7E]ʰ<EC>Ԃ^R<88>
+<CD>ru#<U+063D>"Q<F7><F4>ژ<FA><D0>H<D4><CF><D6>0te<FF><D2>w<F3><97><E6><C6><ED>
\ No newline at end of file
$ echo '*.gpg binary' >> .git-crypt/.gitattributes
$ git show 2c331f3commit 2c331f3c78259d557362e4585acff7260d8ed142
Author: Alexander Dupuy <alex.dupuy@mac.com>
Date:   Tue May 12 14:08:38 2015 +0200

    Add 1 git-crypt collaborator

    New collaborators:

        82A69645 Alexander Dupuy <alex@dupuy.us>

diff --git a/.git-crypt/keys/default/0/083382BAC0059BE3D6544C8B0DCF16F482A69645.
new file mode 100644
index 0000000..9d98379
Binary files /dev/null and b/.git-crypt/keys/default/0/083382BAC0059BE3D6544C8B0
```

**Comment by AGWA** [comment]
Wow, what a freak occurrence for Git to think that was a text file.  Thanks for reporting this and suggesting a fix.  I just incorporated your suggestion.  It will only take effect in new git-crypt repositories - I don't think the problem is severe enough to warrant editing the .gitattributes files of existing repositories (which would be rather tricky).
