### ISSUE TITLE
debian package maintainer ?

### ISSUE THREAD

**Issue by kapouer** [AGWA/git-crypt#57]
Hi,
i wonder if you are planning to upload your software to debian,
and i offer to help reviewing / uploading it.

**Comment by AGWA** [comment]
I would love to have git-crypt in Debian - thanks for offering to sponsor!  I just created an ITP for it:                      
       
 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785346
  
If you want to take a look at the packaging, it's available on the debian branch here:

  https://github.com/AGWA/git-crypt/tree/debian/debian

It's not quite ready for upload - the changelog doesn't close the ITP bug yet, and I need to write a man page for git-crypt, but I'll work on this in the next few days.  Let me know if you'd like me to upload to mentors.debian.net.

**Comment by kapouer** [comment]
Great ! No need to upload to mentors, i'd rather download the release from github and the debian dir from the branch you mentionned. It will be easier if they are kept separated. Thanks !

**Comment by AGWA** [comment]
Hey @kapouer, I just released git-crypt 0.5.0, and the packaging is ready for upload, on the debian branch.  It uses `git-buildpackage` and `pristine-tar`.  Cheers!

**Comment by kapouer** [comment]
@AGWA cool ! if everything's right i'll upload it today.
Since you have a gbp layout here, i don't see why i would need to clone your repo.
On the other hand, if some DD need to make changes to the debian branch, it'd better be
in a known place. What do you think ?

**Comment by kapouer** [comment]
Hey it's so perfectly packaged that i wonder why you're not already DM or DD !

**Comment by kapouer** [comment]
uploaded !

**Comment by kapouer** [comment]
please don't forget to tag your debian branch using `gbp buildpackage --git-tag-only`

**Comment by AGWA** [comment]
Thanks, @kapouer!  I'll probably apply for DM soon (I started contributing last year, and this is my third package in Debian).

I've tagged the debian branch with gbp.  I'd prefer to keep the debian branch together with the upstream repo, if that's OK.

**Comment by kapouer** [comment]
@AGWA  that's fine.
Applying for DM is quite easy, but it will take time before it is processed. Start early !
CC me when you send the DM application mail.

**Comment by kapouer** [comment]
@AGWA it will take some time before the package get accepted in debian.
Do not hesitate to ping me if you release a new version - i can upload it so it's the updated version that gets reviewed before it's accepted by ftp masters.

**Comment by leto** [comment]
Is there a guide to people who want to add non-official apt-get repos so we can install git-crypt via apt-get ? I have a production system that depends on git-crypt and I would prefer for my vagrant provision script to depend on explicit git-crypt releases

**Comment by kapouer** [comment]
As much as i'd like to say yes, i'm not aware of any guide about that.
You will want to clearly separate what you need in two steps:
1) setup an apt repository on a server
2) instruct clients to add an apt source in their /etc/apt dir

Or you could just build the deb and deploy it with dpkg -i the.deb

**Comment by AGWA** [comment]
@leto There isn't a guide specifically for git-crypt, but it's fairly straightforward.

First, you'll need to build a .deb.  This is documented in the INSTALL file, but to summarize:

1. Install git-crypt's dependencies
2. Install the `git-buildpackage` package
3. Check out the debian branch
4. Run `git-buildpackage -uc -us`

Then, as @kapouer says, you'll need to set up an APT repository and add your git-crypt deb to it.  I recommend reprepro for this, and this guide is pretty good: https://wiki.debian.org/SettingUpSignedAptRepositoryWithReprepro

**Comment by kapouer** [comment]
Also you can now (or in a few hours) install git-crypt from debian/sid - and from debian/testing in a few days ! Good job :)
https://buildd.debian.org/status/package.php?p=git-crypt

**Comment by alexcroox** [comment]
What's the easiest way to install this on a continuous deployment Docker image? I'm using debian:jessie and can't find git-crypt via `apt-get` in the normal way.

**Comment by AGWA** [comment]
@alexcroox Stretch was the first release to include git-crypt.  Note that Jessie is going to lose its LTS support at the end of June anyways.

**Comment by alexcroox** [comment]
@AGWA appreciate the response, I'll update my image to Stretch thanks

**Comment by AGWA** [comment]
@alexcroox If you can, upgrade all the way to Buster (the current stable release). It has a newer version of git-crypt and will be supported for longer.
