### ISSUE TITLE
git-crypt unlock doesn't decrypt file

### ISSUE THREAD

**Issue by doender** [AGWA/git-crypt#60]
We have added 2 gpg's by doing:
```git-crypt add-gpg-user USER_ID```

Decrypting works for the first user, but when he pushes it and I pull and run `git-crypt unlock`, I get prompted for the passphrase (MacOS, GPG Suite):

```You need a passphrase to unlock the secret key for```
```user: ...```
```4096-bit RSA key, ID ..., created 2015-08-17 (main key ID ...)```

The program then finishes (no error message) but the file is still encrypted.

**Comment by AGWA** [comment]
Please clarify what you mean by the "The program then finishes."  Do
you mean it doesn't give you a chance to enter your passphrase?

**Comment by doender** [comment]
I can enter my passphrase (and it seems to accept it, because I get an error message when I enter a wrong passphrase). However, it then just finishes and doesn't decrypt the encrypted files.

**Comment by AGWA** [comment]
First, could you try removing the file with `rm` and then checking it out with `git checkout`?  If that successfully decrypts the file, please let me know which version of Git you're using since there may have been a breaking change in Git.

If that doesn't decrypt the file, could you send me the output of `git check-attr -a FILENAME` (replacing FILENAME with the name of the file) and `openssl dgst -sha256 .git/git-crypt/keys/default`.  Please run these commands from the top of both the first user's repository and your repository (after running `git-crypt unlock`).

**Comment by doender** [comment]
I saw I was using an older version of git-crypt (0.4.0). Since I've
upgraded to 0.5.0 everything works fine!

Op di 18 aug. 2015 om 16:41 schreef Andrew Ayer <notifications@github.com>:

**Comment by ava-dylang** [comment]
For posterity, I had a case where a git-crypt enabled file was moved, and the literal encrypted body of the file got committed (I think), so I had a case where git-crypt was succeeding to decrypt the file, but the file was still encrypted. It might be worthwhile to disallow this kind of nested encryption.

**Comment by nolith** [comment]
same here double encryption at work :(

**Comment by Deracination** [comment]
This may be related to GPG not knowing which tty to use to prompt for the passphrase.

I had the same issue and followed the suggestion here: https://superuser.com/a/778586

` export GPG_TTY=$(tty)`

gpg then prompted for the passphrase as expected and files were unlocked.

**Comment by RonquilloAeon** [comment]
@Deracination you saved me! I was getting a `git-crypt: GPG error: Failed to decrypt` error. Turns out that my terminal window was too small for gpg to show the prompt. I made the window larger and all was good.

**Comment by codygman** [comment]
I'm getting this error as well and wonder if it could be related to having a ed25519 gpg key.
