### ISSUE TITLE
please support user-specified gpg executable

### ISSUE THREAD

**Issue by smemsh** [AGWA/git-crypt#65]
On my system, the `gpg` binary is gpg1, but I want to use `gpg2`
(among other reasons, only gpg2 supports elliptic curves).

I looked at gpg.cpp and it looks like you are hardcoding `gpg`
invocations with:

```
    command.push_back("gpg")
    ...
```

I am requesting to have available an environment or command-line
override for the binary path, such as one of the following:

```
    git-crypt --gpg-command=`which gpg2` ...
    GIT_CRYPT_GPG=`which gpg2` git-crypt ...
    git config git-crypt.gpgcmd `which gpg2`
```

**Comment by geowa4** [comment]
I agree; this should be changed. I like your suggestions. As a workaround, I've created a link: `ln -s /usr/local/bin/gpg2 /usr/local/bin/gpg`.

**Comment by ip1981** [comment]
I'd prefer it being configurable at build-time, like

```
MAKE GPG=/path/to/gpgX
```

(defaulting to gpg2, gpg1 is over, really :-))

**Comment by gvalkov** [comment]
Just a data point: the [git-remote-gcrypt](https://github.com/joeyh/git-remote-gcrypt/blob/master/git-remote-gcrypt#L33) project uses the `gpg.program` git config key for this.

**Comment by AGWA** [comment]
Thanks to the PR by @dcreemer, git-crypt now honors the `gpg.program` Git config option.  This is the standard option used by Git to configure the gpg command.

**Comment by ip1981** [comment]
Btw, next gpg will be named gpg, not gpg2 :)
