### ISSUE TITLE
Encrypting all by default, then exclude...

### ISSUE THREAD

**Issue by jaswrks** [AGWA/git-crypt#76]
In the documentation it states...

> Also note that the pattern dir/\* does not match files under sub-directories of dir/. To encrypt an entire sub-tree dir/, place the following in dir/.gitattributes:
> - filter=git-crypt diff=git-crypt
>   .gitattributes !filter !diff
>   The second pattern is essential for ensuring that .gitattributes itself is not encrypted.

I just wanted to point out that you can use `/**` to encrypt deeply. Saves me from needing to create and manage multiple `.gitattributes` files. With this syntax I can dictate everything from a single `.gitattributes` file in the root of the repo.

```
/** filter=git-crypt diff=git-crypt
/public/** !filter !diff
.git* !filter !diff
```

Referencing: https://git-scm.com/docs/gitignore#_pattern_format

So this takes a safety-first approach by encrypting _everything_, but then listing files that should not be encrypted, such as `.git*` files; e.g., `.gitattributes`, `.gitignore`, `.gitmodules`, etc; along with other files or directories that I want to make public.

**Comment by tammersaleh** [comment]
Thank you!  I'd love to see this added to the docs.

**Comment by AGWA** [comment]
Superseded by #156
