### ISSUE TITLE
Only subset of files in .gitattributes get encrypted

### ISSUE THREAD

**Issue by jmstone617** [AGWA/git-crypt#79]
I have a brand new git repository (so, no files staged or committed) with a folder that contains a `.gitattributes` file, which lists a number of files (in both the same directory as the `.gitattributes` file, as well as some sub directories). Only the files in the subdirectories are listed as encrypted when I run `git-crypt status`. I've verified the format in the `.gitattributes` file by adding the same file to `.gitignore` and verifying that it is removed from the list of files to be staged (so, I know it's not a format issue, since the formatting seems to match .gitignore, save for globbing entire subdirectories, as outlined in the documentation). Any insight into why the files at the same directory level as my `.gitattributes` file aren't getting encrypted? I've tried adding `file.ext` as well as `./file.ext` to no avail.

**Comment by AGWA** [comment]
Could you provide the actual contents of your `.gitattributes` file?

**Comment by jmstone617** [comment]
Thanks for the quick reply -- I figured out the issue; it was on my end.
