### ISSUE TITLE
Files are not being encrypted

### ISSUE THREAD

**Issue by tjaskula** [AGWA/git-crypt#91]
Hi,

I followed the documentation to install and configure git-crypt on Mac OS X El Capitan (10.11.6).
Everything was installed correctly (through homebrew).

I want to encrypt a bunch of IPython notebooks, so I made the configuration in `.gitattribues` as follows:

```
.gitattributes !filter !diff
*.ipynb filter=git-crypt diff=git-crypt
```

my `.git/config` file is as follows:

```
[filter "git-crypt"]
	smudge = \"/usr/local/bin/git-crypt\" smudge
	clean = \"/usr/local/bin/git-crypt\" clean
	required = true
[diff "git-crypt"]
	textconv = \"/usr/local/bin/git-crypt\" diff
```

`git-crypt status` shows `*.ipynb` files as encrypted.

Then I commit those files when the encryption should happen.

After pushing it the remote the files are not encrypted.

Any hints on what's going on ?

**Comment by tjaskula** [comment]
After double checking it seems that it works from the command line but not from GitHub Desktop for Mac OS X.

**Comment by JonathanSerafini** [comment]
Hmm well it looks like GitHub Desktop client ships with it's own Git command line client .. so the git-crypt you compiled in for your usual CLI tool wouldn't be available for it. 

If you look at the package, you'll notice that it contains : 
./Resources/git
./Resources/git/bin/git
./Resources/git/libexec/git-core/git

You could always try to replace them with symlinks towards your usual git but that seems a bit hacky and would likely break / be replaced on the next upgrade of the App.

**Comment by tjaskula** [comment]
Thanks for this answer
