### ISSUE TITLE
Add support for GPG card with pin

### ISSUE THREAD

**Issue by abruehl** [AGWA/git-crypt#92]
I have a GPG2 card that requires me to enter a pin each time it encrypts. It appears git-crypt simply fails to encrypt without asking for a pin.

It would be great if support for a GPG card with pin was added.  

In the mean time, I did create a local GPG2 key just for git-crypt.

**Comment by sporkwitch** [comment]
@abruehl You need to correctly configure your gpg and git configurations; this is not an issue with git-crypt. (I use multiple yubikeys myself, no issues on Debian 8, Kubuntu 16.04, Kubuntu 16.10, or Arch).

If you're still having issues, I recommend posting reproduction steps and config files.

**Comment by dkreuer** [comment]
Is there any documentation how to configure git-crypt git and gpg to work with yubikey?

**Comment by sporkwitch** [comment]
Nothing needed on the git-crypt side, and plenty of Googleable guides on how to set up git to use keys stored on a token.

**Comment by abruehl** [comment]
@dkreuer indicates, everything for yubikey is GPG side configuration.  Most of the gotchas I ran into were related to GPG vs GPGv2 configuration and profile vs shell contexts.  you will likely want the graphical pinentry program
